# Generated by Django 5.1.1 on 2025-03-20 11:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("last_modified", models.DateTimeField()),
                ("last_indexed", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.directory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Directories",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("size", models.BigIntegerField(default=0)),
                ("extension", models.CharField(blank=True, max_length=50)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("last_indexed", models.DateTimeField(default=datetime.datetime.now)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "directory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.directory",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Greeting",
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(fields=["path"], name="core_direct_path_39078b_idx"),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(fields=["name"], name="core_direct_name_48494c_idx"),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["parent"], name="core_direct_parent__9ccc40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["name"], name="core_file_name_02f7a3_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["extension"], name="core_file_extensi_98032b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["directory"], name="core_file_directo_b7ec64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["size"], name="core_file_size_4e103d_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["modified_at"], name="core_file_modifie_bf1626_idx"
            ),
        ),
    ]
